=== adeclerk/training/xml/src/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:complexType name="employeeType">
  <xsd:sequence>
      <xsd:element name="empno" type="xsd:int" />
      <xsd:element name="empname" type="xsd:string" />
      <xsd:element name="salary" type="xsd:int" />
  </xsd:sequence>
</xsd:complexType>
    <xsd:element name="organization">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="employee" type="employeeType" minOccurs="1" maxOccurs="5" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== adeclerk/training/xml/src/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<organization xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="employee.xsd">
    <employee>
        <empno>101</empno>
        <empname>John</empname>
        <salary>32000</salary>
    </employee>
    <employee>
        <empno>102</empno>
        <empname>Jack</empname>
        <salary>67000</salary>
    </employee>
    <employee>
        <empno>103</empno>
        <empname>Alex</empname>
        <salary>3939292</salary>
    </employee>
</organization>
