=== adeclerk/training/xml/src/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="person">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="age" type="xsd:int" />
            <xsd:element name="city" type="xsd:string" />
            <xsd:element name="phone" type="xsd:string" minOccurs="1" maxOccurs="5" />
            <xsd:element name="email" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="citizen" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== adeclerk/training/xml/src/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="person.xsd">
    <name>Frank Days</name>
    <age>29</age>
    <city>Orlando</city>
    <phone>321-948-9579</phone>
    <phone>333-333-3333</phone>
    <email>days@gmail.com</email>
    <citizen />
</person>
